{{- if eq .Requirements.webhook "lighthouse" }}
enabled: true
{{- else }}
enabled: false
{{- end }}

hmacToken: "{{ .Parameters.prow.hmacToken }}"

git:
  kind: {{ .Requirements.cluster.gitKind | default "github" }}
  name: {{ .Requirements.cluster.gitName | default "github" }}
  server: {{ .Requirements.cluster.gitServer | default "https://github.com" }}

service:
  name: hook
  
replicaCount: 2

image:
  parentRepository: ghcr.io/jenkins-x
  repository: ghcr.io/jenkins-x/lighthouse
env:
  JX_DEFAULT_IAMGE: ghcr.io/jenkins-x/builder-maven:2.1.155-778-patch3
